In [23]:
from scipy.linalg import hilbert
import numpy as np
from sympy import *

5.1 -31

In [31]:
for i in range(10):
    matrix = hilbert(i+1)
    det = np.linalg.det(matrix)
    print('Det of hilbert hilber matrix (' + str(i+1) + ') \n',matrix)
    print('determinat = ', det)

Det of hilbert hilber matrix (1) 
 [[1.]]
determinat =  1.0
Det of hilbert hilber matrix (2) 
 [[1.         0.5       ]
 [0.5        0.33333333]]
determinat =  0.08333333333333333
Det of hilbert hilber matrix (3) 
 [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
determinat =  0.00046296296296296146
Det of hilbert hilber matrix (4) 
 [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
determinat =  1.6534391534393054e-07
Det of hilbert hilber matrix (5) 
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
determinat =  3.749295132517931e-12
Det of hilbert h

In [32]:
m = Matrix(hilbert(5))
m.rref()

(Matrix([
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]), (0, 1, 2, 3, 4))

5.1 - 32

In [40]:
n = [50, 100, 200, 400]
for i in n:
    a = np.random.rand(i,i)
    b = np.random.randn(i,i)
    
    print('det of rand (' + str(i)+ ') = ', np.linalg.det(a))
    print('det of randn (' + str(i)+ ') = ', np.linalg.det(b))
             

det of rand (50) =  -422618.01860614517
det of randn (50) =  2.330875976865623e+31
det of rand (100) =  6.741716300912184e+24
det of randn (100) =  6.33360033237995e+78
det of rand (200) =  2.1849865164526473e+80
det of randn (200) =  2.900037931444476e+186
det of rand (400) =  1.9470607926094496e+218
det of randn (400) =  -inf


C:\Users\seungwon\Anaconda3\lib\site-packages\numpy\linalg\linalg.py:2010: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)
