In [1]:
from scipy.linalg import hilbert
import numpy as np
from sympy import *
from sympy import Matrix
A = [[2, 3, 5], [-4, 2, 3], [0, 0, 0]]
>>> A = Matrix(A)
>>> A * A.nullspace()[0]

In [42]:
A = np.array([[4, 2, 3], [2,4,3,],[4,4,4]])
A = 0.1 * A
A

array([[0.4, 0.2, 0.3],
       [0.2, 0.4, 0.3],
       [0.4, 0.4, 0.4]])

In [21]:
lamb1 = eye(3)
lamb2 = 0.2 * eye(3) 
lamb3 = 0

In [24]:
A1 = Matrix(A-lamb1)
A2 = Matrix(A-lamb2)
A3 = Matrix(A-lamb3)

In [38]:
print(A1.nullspace())
print(A2.nullspace())
print(A3.nullspace())

[]
[Matrix([
[-1.0],
[   1],
[   0]])]
[Matrix([
[-0.5],
[-0.5],
[   1]])]


In [62]:
for i in range(100):
    if i == 0:
        U = np.dot(A,A)
    else:
        U = np.dot(U,A)
        
print(U)
    
               

[[0.3 0.3 0.3]
 [0.3 0.3 0.3]
 [0.4 0.4 0.4]]
