In [8]:
from scipy.sparse import diags
import numpy as np
from numpy import linalg as LA

In [38]:
# Problem 6.5 : 34

K = diags([-1, 2, -1], [-1, 0, 1], shape=(5, 5)).toarray()
print('5 by 5 matrix from 6.5 D \n K \n= ', K)

l, s = LA.eig(K)
print('\n eigenvalues of K \n lambda = ', l)
trace = np.sum(l)
print('  * trace of K = ', trace)

const = 1
for i in l:
    const = const * i
    det = const
    
print('  * product of eigenvalues (det) = ', det)    
    
print(' ')

print('\n eigenvectors of K \n s = \n', s)

KS = np.matmul(K, s)
print('\n KS \n = ', KS)


5 by 5 matrix from 6.5 D 
 K 
=  [[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]

 eigenvalues of K 
 lambda =  [3.73205081 3.         2.         0.26794919 1.        ]
  * trace of K =  9.999999999999998
  * product of eigenvalues (det) =  5.999999999999987
 

 eigenvectors of K 
 s = 
 [[ 2.88675135e-01  5.00000000e-01  5.77350269e-01  2.88675135e-01
  -5.00000000e-01]
 [-5.00000000e-01 -5.00000000e-01 -8.85199041e-17  5.00000000e-01
  -5.00000000e-01]
 [ 5.77350269e-01  1.92938494e-15 -5.77350269e-01  5.77350269e-01
   1.09260986e-16]
 [-5.00000000e-01  5.00000000e-01 -3.97217852e-16  5.00000000e-01
   5.00000000e-01]
 [ 2.88675135e-01 -5.00000000e-01  5.77350269e-01  2.88675135e-01
   5.00000000e-01]]

 KS 
 =  [[ 1.07735027e+00  1.50000000e+00  1.15470054e+00  7.73502692e-02
  -5.00000000e-01]
 [-1.86602540e+00 -1.50000000e+00  1.11022302e-16  1.33974596e-01
  -5.00000000e-01]
 [ 2.15470054e+00  7.16093851e-15 -1.